[2024-10-01T00:40:57.625+0000] {processor.py:153} INFO - Started process (PID=24825) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T00:40:57.625+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T00:40:57.626+0000] {logging_mixin.py:137} INFO - [2024-10-01T00:40:57.626+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T00:40:57.635+0000] {logging_mixin.py:137} INFO - [2024-10-01T00:40:57.635+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T00:40:57.636+0000] {logging_mixin.py:137} INFO - [2024-10-01T00:40:57.636+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T00:40:57.637+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T00:40:57.646+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2024-10-01T01:57:00.647+0000] {processor.py:153} INFO - Started process (PID=25036) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T01:57:00.648+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T01:57:00.649+0000] {logging_mixin.py:137} INFO - [2024-10-01T01:57:00.649+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T01:57:00.659+0000] {logging_mixin.py:137} INFO - [2024-10-01T01:57:00.659+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T01:57:00.659+0000] {logging_mixin.py:137} INFO - [2024-10-01T01:57:00.659+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T01:57:00.659+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T01:57:00.667+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2024-10-01T03:10:21.613+0000] {processor.py:153} INFO - Started process (PID=25247) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T03:10:21.613+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T03:10:21.614+0000] {logging_mixin.py:137} INFO - [2024-10-01T03:10:21.614+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T03:10:21.622+0000] {logging_mixin.py:137} INFO - [2024-10-01T03:10:21.621+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T03:10:21.623+0000] {logging_mixin.py:137} INFO - [2024-10-01T03:10:21.623+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T03:10:21.623+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T03:10:21.634+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2024-10-01T03:25:03.516+0000] {processor.py:153} INFO - Started process (PID=25458) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T03:25:03.516+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T03:25:03.517+0000] {logging_mixin.py:137} INFO - [2024-10-01T03:25:03.517+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T03:25:03.524+0000] {logging_mixin.py:137} INFO - [2024-10-01T03:25:03.523+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T03:25:03.524+0000] {logging_mixin.py:137} INFO - [2024-10-01T03:25:03.524+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T03:25:03.524+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T03:25:03.533+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2024-10-01T03:25:34.371+0000] {processor.py:153} INFO - Started process (PID=25671) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T03:25:34.371+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T03:25:34.371+0000] {logging_mixin.py:137} INFO - [2024-10-01T03:25:34.371+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T03:25:34.378+0000] {logging_mixin.py:137} INFO - [2024-10-01T03:25:34.378+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T03:25:34.380+0000] {logging_mixin.py:137} INFO - [2024-10-01T03:25:34.380+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T03:25:34.381+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T03:25:34.389+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2024-10-01T03:26:05.049+0000] {processor.py:153} INFO - Started process (PID=25880) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T03:26:05.051+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T03:26:05.051+0000] {logging_mixin.py:137} INFO - [2024-10-01T03:26:05.051+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T03:26:05.059+0000] {logging_mixin.py:137} INFO - [2024-10-01T03:26:05.059+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T03:26:05.059+0000] {logging_mixin.py:137} INFO - [2024-10-01T03:26:05.059+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T03:26:05.060+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T03:26:05.069+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2024-10-01T03:26:35.717+0000] {processor.py:153} INFO - Started process (PID=26091) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T03:26:35.718+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T03:26:35.718+0000] {logging_mixin.py:137} INFO - [2024-10-01T03:26:35.718+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T03:26:35.728+0000] {logging_mixin.py:137} INFO - [2024-10-01T03:26:35.725+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T03:26:35.728+0000] {logging_mixin.py:137} INFO - [2024-10-01T03:26:35.728+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T03:26:35.729+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T03:26:35.738+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2024-10-01T03:58:03.443+0000] {processor.py:153} INFO - Started process (PID=26302) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T03:58:03.443+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T03:58:03.445+0000] {logging_mixin.py:137} INFO - [2024-10-01T03:58:03.445+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T03:58:03.452+0000] {logging_mixin.py:137} INFO - [2024-10-01T03:58:03.451+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T03:58:03.452+0000] {logging_mixin.py:137} INFO - [2024-10-01T03:58:03.452+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T03:58:03.452+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T03:58:03.458+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2024-10-01T05:37:25.497+0000] {processor.py:153} INFO - Started process (PID=26513) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T05:37:25.498+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T05:37:25.498+0000] {logging_mixin.py:137} INFO - [2024-10-01T05:37:25.498+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T05:37:25.507+0000] {logging_mixin.py:137} INFO - [2024-10-01T05:37:25.506+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T05:37:25.508+0000] {logging_mixin.py:137} INFO - [2024-10-01T05:37:25.508+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T05:37:25.508+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T05:37:25.516+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2024-10-01T06:59:35.583+0000] {processor.py:153} INFO - Started process (PID=26724) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T06:59:35.584+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T06:59:35.584+0000] {logging_mixin.py:137} INFO - [2024-10-01T06:59:35.584+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T06:59:35.591+0000] {logging_mixin.py:137} INFO - [2024-10-01T06:59:35.591+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T06:59:35.591+0000] {logging_mixin.py:137} INFO - [2024-10-01T06:59:35.591+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T06:59:35.592+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T06:59:35.598+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2024-10-01T08:40:21.249+0000] {processor.py:153} INFO - Started process (PID=26935) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T08:40:21.253+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T08:40:21.253+0000] {logging_mixin.py:137} INFO - [2024-10-01T08:40:21.253+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T08:40:21.263+0000] {logging_mixin.py:137} INFO - [2024-10-01T08:40:21.259+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T08:40:21.264+0000] {logging_mixin.py:137} INFO - [2024-10-01T08:40:21.264+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T08:40:21.264+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T08:40:21.272+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2024-10-01T10:03:22.562+0000] {processor.py:153} INFO - Started process (PID=27146) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T10:03:22.563+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T10:03:22.564+0000] {logging_mixin.py:137} INFO - [2024-10-01T10:03:22.564+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T10:03:22.575+0000] {logging_mixin.py:137} INFO - [2024-10-01T10:03:22.574+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T10:03:22.575+0000] {logging_mixin.py:137} INFO - [2024-10-01T10:03:22.575+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T10:03:22.576+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T10:03:22.583+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2024-10-01T11:31:46.305+0000] {processor.py:153} INFO - Started process (PID=27357) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T11:31:46.305+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T11:31:46.307+0000] {logging_mixin.py:137} INFO - [2024-10-01T11:31:46.307+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T11:31:46.315+0000] {logging_mixin.py:137} INFO - [2024-10-01T11:31:46.315+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T11:31:46.315+0000] {logging_mixin.py:137} INFO - [2024-10-01T11:31:46.315+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T11:31:46.315+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T11:31:46.325+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2024-10-01T12:39:53.887+0000] {processor.py:153} INFO - Started process (PID=27568) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T12:39:53.888+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T12:39:53.889+0000] {logging_mixin.py:137} INFO - [2024-10-01T12:39:53.889+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T12:39:53.896+0000] {logging_mixin.py:137} INFO - [2024-10-01T12:39:53.895+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T12:39:53.898+0000] {logging_mixin.py:137} INFO - [2024-10-01T12:39:53.898+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T12:39:53.899+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T12:39:53.907+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2024-10-01T15:07:22.771+0000] {processor.py:153} INFO - Started process (PID=345) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:07:22.773+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:07:22.774+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:07:22.774+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:07:22.785+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:07:22.784+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:07:22.785+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:07:22.785+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:07:22.785+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:07:22.792+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2024-10-01T15:07:54.401+0000] {processor.py:153} INFO - Started process (PID=560) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:07:54.404+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:07:54.405+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:07:54.405+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:07:54.420+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:07:54.420+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:07:54.420+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:07:54.420+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:07:54.420+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:07:54.433+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2024-10-01T15:08:25.525+0000] {processor.py:153} INFO - Started process (PID=771) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:08:25.527+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:08:25.528+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:08:25.528+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:08:25.537+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:08:25.537+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:08:25.537+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:08:25.537+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:08:25.537+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:08:25.549+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2024-10-01T15:09:03.683+0000] {processor.py:153} INFO - Started process (PID=982) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:09:03.700+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:09:03.706+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:09:03.705+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:09:03.752+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:09:03.752+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:09:03.753+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:09:03.753+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:09:03.753+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:09:03.792+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.112 seconds
[2024-10-01T15:09:33.982+0000] {processor.py:153} INFO - Started process (PID=1193) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:09:33.984+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:09:33.984+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:09:33.984+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:09:34.001+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:09:34.001+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:09:34.001+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:09:34.001+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:09:34.002+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:09:34.010+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2024-10-01T15:10:04.150+0000] {processor.py:153} INFO - Started process (PID=1404) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:10:04.153+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:10:04.153+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:10:04.153+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:10:04.161+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:10:04.161+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:10:04.161+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:10:04.161+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:10:04.161+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:10:04.172+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2024-10-01T15:10:47.414+0000] {processor.py:153} INFO - Started process (PID=1615) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:10:47.419+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:10:47.426+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:10:47.426+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:10:47.490+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:10:47.488+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:10:47.490+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:10:47.490+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:10:47.491+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:10:47.530+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.197 seconds
[2024-10-01T15:11:19.362+0000] {processor.py:153} INFO - Started process (PID=1825) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:11:19.366+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:11:19.366+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:11:19.366+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:11:19.374+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:11:19.373+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:11:19.374+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:11:19.374+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:11:19.374+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:11:19.384+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2024-10-01T15:12:32.371+0000] {processor.py:153} INFO - Started process (PID=2072) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:12:32.372+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:12:32.372+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:12:32.372+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:12:32.381+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:12:32.381+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:12:32.382+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:12:32.382+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:12:32.382+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:12:32.390+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2024-10-01T15:13:02.909+0000] {processor.py:153} INFO - Started process (PID=2283) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:13:02.909+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:13:02.909+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:13:02.909+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:13:02.979+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:13:02.979+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:13:02.980+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:13:02.980+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:13:02.980+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:13:02.986+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.079 seconds
[2024-10-01T15:13:33.199+0000] {processor.py:153} INFO - Started process (PID=2494) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:13:33.199+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:13:33.200+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:13:33.200+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:13:33.210+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:13:33.210+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:13:33.210+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:13:33.210+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:13:33.210+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:13:33.219+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2024-10-01T15:14:03.991+0000] {processor.py:153} INFO - Started process (PID=2705) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:14:03.992+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:14:03.993+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:14:03.993+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:14:04.001+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:14:04.000+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:14:04.001+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:14:04.001+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:14:04.001+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:14:04.008+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2024-10-01T15:14:34.704+0000] {processor.py:153} INFO - Started process (PID=2918) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:14:34.704+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:14:34.705+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:14:34.705+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:14:34.712+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:14:34.712+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:14:34.712+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:14:34.712+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:14:34.712+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:14:34.717+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2024-10-01T15:15:05.644+0000] {processor.py:153} INFO - Started process (PID=3127) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:15:05.645+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:15:05.647+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:15:05.647+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:15:05.658+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:15:05.658+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:15:05.658+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:15:05.658+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:15:05.658+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:15:05.666+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2024-10-01T15:15:36.387+0000] {processor.py:153} INFO - Started process (PID=3338) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:15:36.387+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:15:36.388+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:15:36.388+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:15:36.395+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:15:36.395+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:15:36.397+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:15:36.397+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:15:36.399+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:15:36.407+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2024-10-01T15:16:07.367+0000] {processor.py:153} INFO - Started process (PID=3551) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:16:07.368+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:16:07.368+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:16:07.368+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:16:07.376+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:16:07.376+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:16:07.378+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:16:07.377+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:16:07.379+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:16:07.388+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2024-10-01T15:16:37.903+0000] {processor.py:153} INFO - Started process (PID=3760) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:16:37.904+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:16:37.904+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:16:37.904+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:16:37.912+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:16:37.912+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:16:37.912+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:16:37.912+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:16:37.913+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:16:37.922+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2024-10-01T15:17:08.557+0000] {processor.py:153} INFO - Started process (PID=3971) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:17:08.558+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:17:08.558+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:17:08.558+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:17:08.565+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:17:08.565+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:17:08.565+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:17:08.565+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:17:08.565+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:17:08.573+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2024-10-01T15:17:39.152+0000] {processor.py:153} INFO - Started process (PID=4182) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:17:39.152+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:17:39.153+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:17:39.153+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:17:39.161+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:17:39.161+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:17:39.162+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:17:39.162+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:17:39.162+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:17:39.167+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2024-10-01T15:18:09.751+0000] {processor.py:153} INFO - Started process (PID=4393) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:18:09.752+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:18:09.752+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:18:09.752+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:18:09.762+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:18:09.762+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:18:09.762+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:18:09.762+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:18:09.762+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:18:09.770+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2024-10-01T15:18:40.308+0000] {processor.py:153} INFO - Started process (PID=4604) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:18:40.309+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:18:40.309+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:18:40.309+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:18:40.318+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:18:40.317+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:18:40.318+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:18:40.318+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:18:40.318+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:18:40.326+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2024-10-01T15:19:10.982+0000] {processor.py:153} INFO - Started process (PID=4815) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:19:10.983+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:19:10.985+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:19:10.985+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:19:10.994+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:19:10.993+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:19:10.994+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:19:10.994+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:19:10.994+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:19:11.002+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2024-10-01T15:19:41.658+0000] {processor.py:153} INFO - Started process (PID=5026) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:19:41.658+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:19:41.659+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:19:41.658+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:19:41.666+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:19:41.666+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:19:41.667+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:19:41.667+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:19:41.670+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:19:41.678+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2024-10-01T15:20:12.329+0000] {processor.py:153} INFO - Started process (PID=5237) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:20:12.332+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:20:12.333+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:20:12.333+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:20:12.341+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:20:12.340+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:20:12.341+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:20:12.341+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:20:12.341+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:20:12.349+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2024-10-01T15:20:42.962+0000] {processor.py:153} INFO - Started process (PID=5448) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:20:42.963+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:20:42.964+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:20:42.964+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:20:42.971+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:20:42.971+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:20:42.972+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:20:42.971+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:20:42.972+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:20:42.980+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2024-10-01T15:21:13.674+0000] {processor.py:153} INFO - Started process (PID=5661) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:21:13.674+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:21:13.674+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:21:13.674+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:21:13.681+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:21:13.681+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:21:13.682+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:21:13.682+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:21:13.682+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:21:13.692+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2024-10-01T15:21:44.395+0000] {processor.py:153} INFO - Started process (PID=5870) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:21:44.396+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:21:44.396+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:21:44.396+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:21:44.405+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:21:44.404+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:21:44.405+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:21:44.405+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:21:44.405+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:21:44.414+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2024-10-01T15:22:15.139+0000] {processor.py:153} INFO - Started process (PID=6081) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:22:15.139+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:22:15.140+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:22:15.140+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:22:15.147+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:22:15.147+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:22:15.148+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:22:15.148+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:22:15.148+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:22:15.157+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2024-10-01T15:22:45.800+0000] {processor.py:153} INFO - Started process (PID=6292) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:22:45.801+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:22:45.802+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:22:45.802+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:22:45.810+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:22:45.810+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:22:45.810+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:22:45.810+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:22:45.810+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:22:45.817+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2024-10-01T15:23:16.466+0000] {processor.py:153} INFO - Started process (PID=6503) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:23:16.468+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:23:16.469+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:23:16.469+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:23:16.477+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:23:16.477+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:23:16.477+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:23:16.477+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:23:16.477+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:23:16.485+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2024-10-01T15:23:47.039+0000] {processor.py:153} INFO - Started process (PID=6714) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:23:47.041+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:23:47.041+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:23:47.041+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:23:47.048+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:23:47.048+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:23:47.048+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:23:47.048+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:23:47.049+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:23:47.056+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2024-10-01T15:24:17.688+0000] {processor.py:153} INFO - Started process (PID=6925) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:24:17.690+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:24:17.690+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:24:17.690+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:24:17.700+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:24:17.700+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:24:17.701+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:24:17.701+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:24:17.701+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:24:17.708+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2024-10-01T15:24:48.282+0000] {processor.py:153} INFO - Started process (PID=7136) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:24:48.283+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:24:48.283+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:24:48.283+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:24:48.291+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:24:48.290+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:24:48.291+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:24:48.291+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:24:48.291+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:24:48.296+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2024-10-01T15:25:18.918+0000] {processor.py:153} INFO - Started process (PID=7347) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:25:18.919+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:25:18.919+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:25:18.919+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:25:18.928+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:25:18.927+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:25:18.928+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:25:18.928+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:25:18.928+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:25:18.933+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2024-10-01T15:25:49.575+0000] {processor.py:153} INFO - Started process (PID=7558) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:25:49.577+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:25:49.577+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:25:49.577+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:25:49.586+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:25:49.585+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:25:49.586+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:25:49.586+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:25:49.586+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:25:49.594+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2024-10-01T15:26:20.076+0000] {processor.py:153} INFO - Started process (PID=7769) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:26:20.076+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:26:20.077+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:26:20.077+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:26:20.085+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:26:20.084+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:26:20.085+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:26:20.085+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:26:20.085+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:26:20.094+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2024-10-01T15:26:50.745+0000] {processor.py:153} INFO - Started process (PID=7980) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:26:50.746+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:26:50.747+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:26:50.747+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:26:50.754+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:26:50.754+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:26:50.754+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:26:50.754+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:26:50.754+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:26:50.760+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2024-10-01T15:27:21.469+0000] {processor.py:153} INFO - Started process (PID=8191) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:27:21.470+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:27:21.470+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:27:21.470+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:27:21.478+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:27:21.477+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:27:21.478+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:27:21.478+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:27:21.478+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:27:21.483+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2024-10-01T15:27:52.285+0000] {processor.py:153} INFO - Started process (PID=8402) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:27:52.290+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:27:52.291+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:27:52.291+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:27:52.310+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:27:52.310+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:27:52.310+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:27:52.310+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:27:52.310+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:27:52.317+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2024-10-01T15:28:22.470+0000] {processor.py:153} INFO - Started process (PID=8615) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:28:22.470+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:28:22.470+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:28:22.470+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:28:22.478+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:28:22.477+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:28:22.478+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:28:22.478+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:28:22.478+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:28:22.484+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2024-10-01T15:28:53.320+0000] {processor.py:153} INFO - Started process (PID=8824) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:28:53.323+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:28:53.323+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:28:53.323+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:28:53.331+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:28:53.330+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:28:53.331+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:28:53.331+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:28:53.331+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:28:53.338+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2024-10-01T15:29:24.295+0000] {processor.py:153} INFO - Started process (PID=9035) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:29:24.296+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:29:24.297+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:29:24.297+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:29:24.306+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:29:24.306+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:29:24.307+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:29:24.307+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:29:24.307+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:29:24.317+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2024-10-01T15:29:55.129+0000] {processor.py:153} INFO - Started process (PID=9246) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:29:55.132+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:29:55.132+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:29:55.132+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:29:55.139+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:29:55.139+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:29:55.139+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:29:55.139+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:29:55.140+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:29:55.148+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2024-10-01T15:30:25.866+0000] {processor.py:153} INFO - Started process (PID=9457) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:30:25.867+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:30:25.867+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:30:25.867+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:30:25.875+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:30:25.875+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:30:25.876+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:30:25.875+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:30:25.877+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:30:25.885+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2024-10-01T15:30:56.600+0000] {processor.py:153} INFO - Started process (PID=9668) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:30:56.601+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:30:56.602+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:30:56.602+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:30:56.609+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:30:56.609+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:30:56.609+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:30:56.609+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:30:56.610+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:30:56.618+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2024-10-01T15:31:27.536+0000] {processor.py:153} INFO - Started process (PID=9879) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:31:27.537+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:31:27.537+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:31:27.537+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:31:27.546+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:31:27.546+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:31:27.547+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:31:27.546+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:31:27.548+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:31:27.554+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2024-10-01T15:31:58.060+0000] {processor.py:153} INFO - Started process (PID=10090) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:31:58.062+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:31:58.063+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:31:58.063+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:31:58.071+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:31:58.071+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:31:58.071+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:31:58.071+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:31:58.072+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:31:58.077+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2024-10-01T15:32:28.817+0000] {processor.py:153} INFO - Started process (PID=10301) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:32:28.817+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:32:28.818+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:32:28.818+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:32:28.826+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:32:28.826+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:32:28.826+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:32:28.826+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:32:28.827+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:32:28.833+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2024-10-01T15:32:59.685+0000] {processor.py:153} INFO - Started process (PID=10512) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:32:59.686+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:32:59.687+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:32:59.687+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:32:59.698+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:32:59.698+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:32:59.698+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:32:59.698+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:32:59.699+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:32:59.705+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2024-10-01T15:33:29.879+0000] {processor.py:153} INFO - Started process (PID=10723) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:33:29.880+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:33:29.880+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:33:29.880+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:33:29.893+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:33:29.893+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:33:29.893+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:33:29.893+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:33:29.894+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:33:29.908+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2024-10-01T15:34:00.004+0000] {processor.py:153} INFO - Started process (PID=10934) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:34:00.006+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:34:00.006+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:34:00.006+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:34:00.014+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:34:00.013+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:34:00.014+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:34:00.014+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:34:00.014+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:34:00.023+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2024-10-01T15:34:30.233+0000] {processor.py:153} INFO - Started process (PID=11145) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:34:30.234+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:34:30.234+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:34:30.234+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:34:30.253+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:34:30.252+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:34:30.253+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:34:30.253+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:34:30.254+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:34:30.270+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2024-10-01T15:35:01.274+0000] {processor.py:153} INFO - Started process (PID=11356) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:35:01.275+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:35:01.277+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:35:01.276+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:35:01.294+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:35:01.293+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:35:01.294+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:35:01.294+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:35:01.299+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:35:01.313+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2024-10-01T15:35:32.093+0000] {processor.py:153} INFO - Started process (PID=11565) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:35:32.095+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:35:32.096+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:35:32.096+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:35:32.110+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:35:32.110+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:35:32.111+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:35:32.110+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:35:32.111+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:35:32.122+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2024-10-01T15:36:02.721+0000] {processor.py:153} INFO - Started process (PID=11778) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:36:02.727+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:36:02.727+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:36:02.727+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:36:02.738+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:36:02.738+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:36:02.738+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:36:02.738+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:36:02.739+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:36:02.746+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2024-10-01T15:36:33.451+0000] {processor.py:153} INFO - Started process (PID=11989) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:36:33.453+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:36:33.456+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:36:33.456+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:36:33.468+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:36:33.467+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:36:33.469+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:36:33.468+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:36:33.472+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:36:33.483+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2024-10-01T15:37:04.408+0000] {processor.py:153} INFO - Started process (PID=12200) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:37:04.410+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:37:04.412+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:37:04.412+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:37:04.425+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:37:04.425+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:37:04.428+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:37:04.428+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:37:04.429+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:37:04.437+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2024-10-01T15:37:35.370+0000] {processor.py:153} INFO - Started process (PID=12411) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:37:35.374+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:37:35.375+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:37:35.375+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:37:35.388+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:37:35.387+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:37:35.389+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:37:35.389+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:37:35.390+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:37:35.400+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2024-10-01T15:38:06.026+0000] {processor.py:153} INFO - Started process (PID=12622) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:38:06.027+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:38:06.028+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:38:06.028+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:38:06.041+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:38:06.040+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:38:06.042+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:38:06.042+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:38:06.044+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:38:06.054+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2024-10-01T15:38:36.820+0000] {processor.py:153} INFO - Started process (PID=12832) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:38:36.823+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:38:36.824+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:38:36.824+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:38:36.837+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:38:36.836+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:38:36.837+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:38:36.837+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:38:36.838+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:38:36.854+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2024-10-01T15:39:07.508+0000] {processor.py:153} INFO - Started process (PID=13044) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:39:07.510+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:39:07.511+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:39:07.511+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:39:07.524+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:39:07.523+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:39:07.526+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:39:07.526+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:39:07.527+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:39:07.537+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2024-10-01T15:39:38.301+0000] {processor.py:153} INFO - Started process (PID=13255) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:39:38.306+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:39:38.308+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:39:38.308+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:39:38.319+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:39:38.318+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:39:38.319+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:39:38.319+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:39:38.319+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:39:38.326+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2024-10-01T15:40:09.214+0000] {processor.py:153} INFO - Started process (PID=13466) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:40:09.216+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:40:09.217+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:40:09.217+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:40:09.231+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:40:09.231+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:40:09.233+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:40:09.233+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:40:09.235+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:40:09.252+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2024-10-01T15:40:40.098+0000] {processor.py:153} INFO - Started process (PID=13677) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:40:40.099+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:40:40.100+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:40:40.100+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:40:40.114+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:40:40.114+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:40:40.114+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:40:40.114+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:40:40.115+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:40:40.145+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.050 seconds
[2024-10-01T15:41:10.985+0000] {processor.py:153} INFO - Started process (PID=13888) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:41:10.987+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:41:10.988+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:41:10.988+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:41:10.999+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:41:10.999+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:41:11.000+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:41:10.999+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:41:11.003+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:41:11.016+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2024-10-01T15:41:41.130+0000] {processor.py:153} INFO - Started process (PID=14096) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:41:41.132+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:41:41.133+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:41:41.132+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:41:41.145+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:41:41.145+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:41:41.146+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:41:41.146+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:41:41.148+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:41:41.157+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2024-10-01T15:42:11.879+0000] {processor.py:153} INFO - Started process (PID=14310) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:42:11.880+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:42:11.880+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:42:11.880+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:42:11.889+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:42:11.889+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:42:11.889+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:42:11.889+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:42:11.890+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:42:11.896+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2024-10-01T15:42:42.643+0000] {processor.py:153} INFO - Started process (PID=14521) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:42:42.649+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:42:42.651+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:42:42.651+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:42:42.662+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:42:42.661+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:42:42.662+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:42:42.662+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:42:42.662+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:42:42.670+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2024-10-01T15:43:13.370+0000] {processor.py:153} INFO - Started process (PID=14731) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:43:13.375+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:43:13.376+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:43:13.376+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:43:13.387+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:43:13.386+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:43:13.387+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:43:13.387+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:43:13.387+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:43:13.395+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2024-10-01T15:43:43.423+0000] {processor.py:153} INFO - Started process (PID=14938) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:43:43.424+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:43:43.424+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:43:43.424+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:43:43.431+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:43:43.431+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:43:43.432+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:43:43.432+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:43:43.432+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:43:43.439+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2024-10-01T15:44:13.536+0000] {processor.py:153} INFO - Started process (PID=15149) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:44:13.537+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:44:13.537+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:44:13.537+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:44:13.544+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:44:13.544+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:44:13.545+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:44:13.544+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:44:13.545+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:44:13.549+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2024-10-01T15:44:44.368+0000] {processor.py:153} INFO - Started process (PID=15360) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:44:44.368+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:44:44.370+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:44:44.370+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:44:44.377+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:44:44.377+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:44:44.377+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:44:44.377+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:44:44.377+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:44:44.382+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2024-10-01T15:45:14.748+0000] {processor.py:153} INFO - Started process (PID=15571) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:45:14.749+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:45:14.749+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:45:14.749+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:45:14.759+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:45:14.758+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:45:14.759+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:45:14.759+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:45:14.759+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:45:14.764+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2024-10-01T15:45:45.623+0000] {processor.py:153} INFO - Started process (PID=15782) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:45:45.623+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:45:45.624+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:45:45.624+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:45:45.633+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:45:45.633+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:45:45.633+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:45:45.633+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:45:45.633+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:45:45.642+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2024-10-01T15:46:16.708+0000] {processor.py:153} INFO - Started process (PID=15993) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:46:16.710+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:46:16.710+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:46:16.710+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:46:16.717+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:46:16.717+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:46:16.717+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:46:16.717+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:46:16.717+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:46:16.723+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2024-10-01T15:46:47.567+0000] {processor.py:153} INFO - Started process (PID=16204) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:46:47.568+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:46:47.568+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:46:47.568+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:46:47.575+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:46:47.575+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:46:47.576+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:46:47.576+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:46:47.576+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:46:47.581+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2024-10-01T15:47:18.497+0000] {processor.py:153} INFO - Started process (PID=16415) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:47:18.498+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:47:18.499+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:47:18.499+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:47:18.508+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:47:18.508+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:47:18.509+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:47:18.509+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:47:18.509+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:47:18.520+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2024-10-01T15:47:49.227+0000] {processor.py:153} INFO - Started process (PID=16626) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:47:49.227+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:47:49.228+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:47:49.228+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:47:49.235+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:47:49.235+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:47:49.236+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:47:49.236+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:47:49.236+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:47:49.241+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2024-10-01T15:48:19.666+0000] {processor.py:153} INFO - Started process (PID=16837) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:48:19.669+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:48:19.669+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:48:19.669+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:48:19.679+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:48:19.679+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:48:19.681+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:48:19.681+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:48:19.681+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:48:19.690+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2024-10-01T15:48:50.575+0000] {processor.py:153} INFO - Started process (PID=17048) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:48:50.575+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:48:50.576+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:48:50.576+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:48:50.584+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:48:50.583+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:48:50.584+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:48:50.584+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:48:50.584+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:48:50.590+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2024-10-01T15:49:21.630+0000] {processor.py:153} INFO - Started process (PID=17261) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:49:21.630+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:49:21.631+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:49:21.631+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:49:21.637+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:49:21.637+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:49:21.637+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:49:21.637+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:49:21.637+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:49:21.642+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.014 seconds
[2024-10-01T15:49:52.340+0000] {processor.py:153} INFO - Started process (PID=17470) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:49:52.341+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:49:52.341+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:49:52.341+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:49:52.349+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:49:52.348+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:49:52.349+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:49:52.349+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:49:52.350+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:49:52.358+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2024-10-01T15:50:22.965+0000] {processor.py:153} INFO - Started process (PID=17683) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:50:22.965+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:50:22.965+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:50:22.965+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:50:22.975+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:50:22.975+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:50:22.975+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:50:22.975+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:50:22.976+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:50:22.983+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2024-10-01T15:50:53.708+0000] {processor.py:153} INFO - Started process (PID=17892) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:50:53.709+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:50:53.710+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:50:53.710+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:50:53.717+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:50:53.717+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:50:53.719+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:50:53.718+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:50:53.719+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:50:53.727+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2024-10-01T15:51:23.940+0000] {processor.py:153} INFO - Started process (PID=18103) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:51:23.944+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:51:23.945+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:51:23.945+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:51:23.952+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:51:23.952+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:51:23.953+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:51:23.952+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:51:23.953+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:51:23.964+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2024-10-01T15:51:54.631+0000] {processor.py:153} INFO - Started process (PID=18314) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:51:54.633+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:51:54.633+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:51:54.633+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:51:54.642+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:51:54.642+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:51:54.642+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:51:54.642+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:51:54.642+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:51:54.653+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2024-10-01T15:52:25.556+0000] {processor.py:153} INFO - Started process (PID=18527) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:52:25.556+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:52:25.557+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:52:25.556+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:52:25.564+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:52:25.563+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:52:25.564+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:52:25.564+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:52:25.564+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:52:25.572+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2024-10-01T15:52:56.192+0000] {processor.py:153} INFO - Started process (PID=18736) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:52:56.193+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:52:56.194+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:52:56.193+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:52:56.203+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:52:56.203+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:52:56.203+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:52:56.203+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:52:56.203+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:52:56.211+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2024-10-01T15:53:26.764+0000] {processor.py:153} INFO - Started process (PID=18947) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:53:26.765+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:53:26.765+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:53:26.765+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:53:26.772+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:53:26.772+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:53:26.773+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:53:26.772+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:53:26.773+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:53:26.777+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2024-10-01T15:53:57.422+0000] {processor.py:153} INFO - Started process (PID=19158) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:53:57.423+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:53:57.424+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:53:57.424+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:53:57.433+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:53:57.432+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:53:57.433+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:53:57.433+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:53:57.433+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:53:57.441+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2024-10-01T15:54:28.097+0000] {processor.py:153} INFO - Started process (PID=19369) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:54:28.097+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:54:28.097+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:54:28.097+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:54:28.105+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:54:28.104+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:54:28.105+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:54:28.105+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:54:28.105+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:54:28.110+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2024-10-01T15:54:58.761+0000] {processor.py:153} INFO - Started process (PID=19582) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:54:58.761+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:54:58.762+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:54:58.762+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:54:58.768+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:54:58.768+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:54:58.768+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:54:58.768+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:54:58.768+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:54:58.773+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.014 seconds
[2024-10-01T15:55:29.338+0000] {processor.py:153} INFO - Started process (PID=19793) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:55:29.338+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:55:29.339+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:55:29.339+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:55:29.347+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:55:29.347+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:55:29.348+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:55:29.348+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:55:29.348+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:55:29.356+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2024-10-01T15:55:59.974+0000] {processor.py:153} INFO - Started process (PID=20004) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:55:59.975+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:55:59.975+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:55:59.975+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:55:59.983+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:55:59.982+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:55:59.984+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:55:59.983+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:55:59.984+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:55:59.989+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2024-10-01T15:56:30.533+0000] {processor.py:153} INFO - Started process (PID=20215) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:56:30.533+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:56:30.534+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:56:30.534+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:56:30.540+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:56:30.540+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:56:30.540+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:56:30.540+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:56:30.540+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:56:30.545+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.014 seconds
[2024-10-01T15:57:01.254+0000] {processor.py:153} INFO - Started process (PID=20424) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:57:01.254+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:57:01.255+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:57:01.255+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:57:01.262+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:57:01.262+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:57:01.263+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:57:01.263+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:57:01.263+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:57:01.269+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2024-10-01T15:57:32.184+0000] {processor.py:153} INFO - Started process (PID=20635) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:57:32.185+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:57:32.186+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:57:32.186+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:57:32.194+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:57:32.193+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:57:32.194+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:57:32.194+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:57:32.194+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:57:32.199+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2024-10-01T15:58:03.110+0000] {processor.py:153} INFO - Started process (PID=20846) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:58:03.111+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:58:03.112+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:58:03.112+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:58:03.119+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:58:03.119+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:58:03.119+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:58:03.119+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:58:03.119+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:58:03.127+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2024-10-01T15:58:33.832+0000] {processor.py:153} INFO - Started process (PID=21057) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:58:33.834+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:58:33.834+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:58:33.834+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:58:33.841+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:58:33.841+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:58:33.841+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:58:33.841+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:58:33.841+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:58:33.848+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2024-10-01T15:59:04.500+0000] {processor.py:153} INFO - Started process (PID=21270) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:59:04.501+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:59:04.501+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:59:04.501+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:59:04.508+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:59:04.508+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:59:04.508+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:59:04.508+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:59:04.508+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:59:04.514+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2024-10-01T15:59:35.253+0000] {processor.py:153} INFO - Started process (PID=21479) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:59:35.254+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T15:59:35.255+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:59:35.255+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:59:35.262+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:59:35.262+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T15:59:35.262+0000] {logging_mixin.py:137} INFO - [2024-10-01T15:59:35.262+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T15:59:35.262+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T15:59:35.269+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2024-10-01T16:00:05.978+0000] {processor.py:153} INFO - Started process (PID=21692) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T16:00:05.979+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T16:00:05.979+0000] {logging_mixin.py:137} INFO - [2024-10-01T16:00:05.979+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T16:00:05.986+0000] {logging_mixin.py:137} INFO - [2024-10-01T16:00:05.985+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T16:00:05.986+0000] {logging_mixin.py:137} INFO - [2024-10-01T16:00:05.986+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T16:00:05.986+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T16:00:05.991+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.014 seconds
