[2024-09-24T15:58:44.710+0000] {processor.py:153} INFO - Started process (PID=349) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T15:58:44.710+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-24T15:58:44.711+0000] {logging_mixin.py:137} INFO - [2024-09-24T15:58:44.711+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T15:58:44.720+0000] {logging_mixin.py:137} INFO - [2024-09-24T15:58:44.719+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-24T15:58:44.720+0000] {logging_mixin.py:137} INFO - [2024-09-24T15:58:44.720+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-24T15:58:44.721+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T15:58:44.729+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2024-09-24T15:59:15.222+0000] {processor.py:153} INFO - Started process (PID=562) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T15:59:15.226+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-24T15:59:15.228+0000] {logging_mixin.py:137} INFO - [2024-09-24T15:59:15.228+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T15:59:15.264+0000] {logging_mixin.py:137} INFO - [2024-09-24T15:59:15.264+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-24T15:59:15.268+0000] {logging_mixin.py:137} INFO - [2024-09-24T15:59:15.268+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-24T15:59:15.272+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T15:59:15.353+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.133 seconds
[2024-09-24T15:59:46.418+0000] {processor.py:153} INFO - Started process (PID=773) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T15:59:46.419+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-24T15:59:46.420+0000] {logging_mixin.py:137} INFO - [2024-09-24T15:59:46.420+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T15:59:46.428+0000] {logging_mixin.py:137} INFO - [2024-09-24T15:59:46.427+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-24T15:59:46.430+0000] {logging_mixin.py:137} INFO - [2024-09-24T15:59:46.430+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-24T15:59:46.430+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T15:59:46.437+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2024-09-24T16:12:38.821+0000] {processor.py:153} INFO - Started process (PID=350) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T16:12:38.823+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-24T16:12:38.823+0000] {logging_mixin.py:137} INFO - [2024-09-24T16:12:38.823+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T16:12:38.839+0000] {logging_mixin.py:137} INFO - [2024-09-24T16:12:38.837+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-24T16:12:38.839+0000] {logging_mixin.py:137} INFO - [2024-09-24T16:12:38.839+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-24T16:12:38.840+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T16:12:38.854+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2024-09-24T16:13:23.178+0000] {processor.py:153} INFO - Started process (PID=563) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T16:13:23.180+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-24T16:13:23.184+0000] {logging_mixin.py:137} INFO - [2024-09-24T16:13:23.183+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T16:13:23.245+0000] {logging_mixin.py:137} INFO - [2024-09-24T16:13:23.243+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-24T16:13:23.256+0000] {logging_mixin.py:137} INFO - [2024-09-24T16:13:23.254+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-24T16:13:23.265+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T16:13:23.292+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.116 seconds
[2024-09-24T16:13:53.472+0000] {processor.py:153} INFO - Started process (PID=772) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T16:13:53.483+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-24T16:13:53.486+0000] {logging_mixin.py:137} INFO - [2024-09-24T16:13:53.485+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T16:13:53.498+0000] {logging_mixin.py:137} INFO - [2024-09-24T16:13:53.497+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-24T16:13:53.498+0000] {logging_mixin.py:137} INFO - [2024-09-24T16:13:53.498+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-24T16:13:53.499+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T16:13:53.516+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2024-09-24T16:14:26.049+0000] {processor.py:153} INFO - Started process (PID=983) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T16:14:26.051+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-24T16:14:26.053+0000] {logging_mixin.py:137} INFO - [2024-09-24T16:14:26.053+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T16:14:26.097+0000] {logging_mixin.py:137} INFO - [2024-09-24T16:14:26.096+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-24T16:14:26.097+0000] {logging_mixin.py:137} INFO - [2024-09-24T16:14:26.097+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-24T16:14:26.098+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T16:14:26.163+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.119 seconds
[2024-09-24T16:15:05.056+0000] {processor.py:153} INFO - Started process (PID=1194) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T16:15:05.057+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-24T16:15:05.060+0000] {logging_mixin.py:137} INFO - [2024-09-24T16:15:05.059+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T16:15:05.086+0000] {logging_mixin.py:137} INFO - [2024-09-24T16:15:05.084+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-24T16:15:05.086+0000] {logging_mixin.py:137} INFO - [2024-09-24T16:15:05.086+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-24T16:15:05.088+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T16:15:05.100+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.051 seconds
[2024-09-24T16:15:37.191+0000] {processor.py:153} INFO - Started process (PID=1405) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T16:15:37.192+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-24T16:15:37.206+0000] {logging_mixin.py:137} INFO - [2024-09-24T16:15:37.206+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T16:15:37.218+0000] {logging_mixin.py:137} INFO - [2024-09-24T16:15:37.217+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-24T16:15:37.218+0000] {logging_mixin.py:137} INFO - [2024-09-24T16:15:37.218+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-24T16:15:37.218+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T16:15:37.225+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2024-09-24T16:16:07.550+0000] {processor.py:153} INFO - Started process (PID=1616) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T16:16:07.552+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-24T16:16:07.552+0000] {logging_mixin.py:137} INFO - [2024-09-24T16:16:07.552+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T16:16:07.566+0000] {logging_mixin.py:137} INFO - [2024-09-24T16:16:07.566+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-24T16:16:07.566+0000] {logging_mixin.py:137} INFO - [2024-09-24T16:16:07.566+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-24T16:16:07.566+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T16:16:07.572+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2024-09-24T16:16:37.876+0000] {processor.py:153} INFO - Started process (PID=1824) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T16:16:37.877+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-24T16:16:37.878+0000] {logging_mixin.py:137} INFO - [2024-09-24T16:16:37.877+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T16:16:37.884+0000] {logging_mixin.py:137} INFO - [2024-09-24T16:16:37.884+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-24T16:16:37.884+0000] {logging_mixin.py:137} INFO - [2024-09-24T16:16:37.884+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-24T16:16:37.885+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T16:16:37.890+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2024-09-24T16:17:08.415+0000] {processor.py:153} INFO - Started process (PID=2038) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T16:17:08.419+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-24T16:17:08.421+0000] {logging_mixin.py:137} INFO - [2024-09-24T16:17:08.421+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T16:17:08.428+0000] {logging_mixin.py:137} INFO - [2024-09-24T16:17:08.428+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-24T16:17:08.430+0000] {logging_mixin.py:137} INFO - [2024-09-24T16:17:08.430+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-24T16:17:08.431+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T16:17:08.443+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2024-09-24T16:17:39.152+0000] {processor.py:153} INFO - Started process (PID=2246) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T16:17:39.153+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-24T16:17:39.153+0000] {logging_mixin.py:137} INFO - [2024-09-24T16:17:39.153+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T16:17:39.161+0000] {logging_mixin.py:137} INFO - [2024-09-24T16:17:39.160+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-24T16:17:39.161+0000] {logging_mixin.py:137} INFO - [2024-09-24T16:17:39.161+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-24T16:17:39.161+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T16:17:39.167+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2024-09-24T16:18:09.753+0000] {processor.py:153} INFO - Started process (PID=2455) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T16:18:09.754+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-24T16:18:09.754+0000] {logging_mixin.py:137} INFO - [2024-09-24T16:18:09.754+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T16:18:09.822+0000] {logging_mixin.py:137} INFO - [2024-09-24T16:18:09.822+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-24T16:18:09.824+0000] {logging_mixin.py:137} INFO - [2024-09-24T16:18:09.824+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-24T16:18:09.825+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T16:18:09.836+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.084 seconds
[2024-09-24T17:55:52.033+0000] {processor.py:153} INFO - Started process (PID=347) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T17:55:52.034+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-24T17:55:52.035+0000] {logging_mixin.py:137} INFO - [2024-09-24T17:55:52.034+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T17:55:52.042+0000] {logging_mixin.py:137} INFO - [2024-09-24T17:55:52.042+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-24T17:55:52.043+0000] {logging_mixin.py:137} INFO - [2024-09-24T17:55:52.042+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-24T17:55:52.043+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T17:55:52.048+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2024-09-24T17:56:26.468+0000] {processor.py:153} INFO - Started process (PID=560) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T17:56:26.476+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-24T17:56:26.488+0000] {logging_mixin.py:137} INFO - [2024-09-24T17:56:26.487+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T17:56:26.536+0000] {logging_mixin.py:137} INFO - [2024-09-24T17:56:26.535+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-24T17:56:26.536+0000] {logging_mixin.py:137} INFO - [2024-09-24T17:56:26.536+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-24T17:56:26.537+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T17:56:26.553+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.087 seconds
[2024-09-24T18:44:47.492+0000] {processor.py:153} INFO - Started process (PID=350) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T18:44:47.493+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-24T18:44:47.493+0000] {logging_mixin.py:137} INFO - [2024-09-24T18:44:47.493+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T18:44:47.547+0000] {logging_mixin.py:137} INFO - [2024-09-24T18:44:47.539+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-24T18:44:47.548+0000] {logging_mixin.py:137} INFO - [2024-09-24T18:44:47.548+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-24T18:44:47.550+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T18:44:47.608+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.119 seconds
[2024-09-24T18:45:18.534+0000] {processor.py:153} INFO - Started process (PID=567) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T18:45:18.538+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-24T18:45:18.538+0000] {logging_mixin.py:137} INFO - [2024-09-24T18:45:18.538+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T18:45:18.567+0000] {logging_mixin.py:137} INFO - [2024-09-24T18:45:18.565+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-24T18:45:18.567+0000] {logging_mixin.py:137} INFO - [2024-09-24T18:45:18.567+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-24T18:45:18.567+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T18:45:18.579+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.047 seconds
[2024-09-24T18:45:50.231+0000] {processor.py:153} INFO - Started process (PID=776) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T18:45:50.233+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-24T18:45:50.233+0000] {logging_mixin.py:137} INFO - [2024-09-24T18:45:50.233+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T18:45:50.245+0000] {logging_mixin.py:137} INFO - [2024-09-24T18:45:50.244+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-24T18:45:50.245+0000] {logging_mixin.py:137} INFO - [2024-09-24T18:45:50.245+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-24T18:45:50.245+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T18:45:50.256+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2024-09-24T18:46:21.128+0000] {processor.py:153} INFO - Started process (PID=987) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T18:46:21.130+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-24T18:46:21.130+0000] {logging_mixin.py:137} INFO - [2024-09-24T18:46:21.130+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T18:46:21.142+0000] {logging_mixin.py:137} INFO - [2024-09-24T18:46:21.142+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-24T18:46:21.142+0000] {logging_mixin.py:137} INFO - [2024-09-24T18:46:21.142+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-24T18:46:21.142+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T18:46:21.151+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2024-09-24T18:46:55.044+0000] {processor.py:153} INFO - Started process (PID=1198) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T18:46:55.046+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-24T18:46:55.047+0000] {logging_mixin.py:137} INFO - [2024-09-24T18:46:55.047+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T18:46:55.068+0000] {logging_mixin.py:137} INFO - [2024-09-24T18:46:55.067+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-24T18:46:55.079+0000] {logging_mixin.py:137} INFO - [2024-09-24T18:46:55.079+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-24T18:46:55.085+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T18:46:55.206+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.166 seconds
[2024-09-24T18:47:28.985+0000] {processor.py:153} INFO - Started process (PID=1408) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T18:47:29.001+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-24T18:47:29.003+0000] {logging_mixin.py:137} INFO - [2024-09-24T18:47:29.003+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T18:47:29.033+0000] {logging_mixin.py:137} INFO - [2024-09-24T18:47:29.031+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-24T18:47:29.033+0000] {logging_mixin.py:137} INFO - [2024-09-24T18:47:29.033+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-24T18:47:29.034+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T18:47:29.067+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.089 seconds
[2024-09-24T18:48:00.755+0000] {processor.py:153} INFO - Started process (PID=1620) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T18:48:00.757+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-24T18:48:00.757+0000] {logging_mixin.py:137} INFO - [2024-09-24T18:48:00.757+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T18:48:00.767+0000] {logging_mixin.py:137} INFO - [2024-09-24T18:48:00.767+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-24T18:48:00.768+0000] {logging_mixin.py:137} INFO - [2024-09-24T18:48:00.768+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-24T18:48:00.769+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T18:48:00.777+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2024-09-24T18:48:31.558+0000] {processor.py:153} INFO - Started process (PID=1830) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T18:48:31.560+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-24T18:48:31.560+0000] {logging_mixin.py:137} INFO - [2024-09-24T18:48:31.560+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T18:48:31.568+0000] {logging_mixin.py:137} INFO - [2024-09-24T18:48:31.568+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-24T18:48:31.568+0000] {logging_mixin.py:137} INFO - [2024-09-24T18:48:31.568+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-24T18:48:31.568+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T18:48:31.575+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2024-09-24T18:49:03.007+0000] {processor.py:153} INFO - Started process (PID=2036) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T18:49:03.010+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-24T18:49:03.010+0000] {logging_mixin.py:137} INFO - [2024-09-24T18:49:03.010+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T18:49:03.024+0000] {logging_mixin.py:137} INFO - [2024-09-24T18:49:03.023+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-24T18:49:03.024+0000] {logging_mixin.py:137} INFO - [2024-09-24T18:49:03.024+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-24T18:49:03.024+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T18:49:03.037+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2024-09-24T18:49:34.058+0000] {processor.py:153} INFO - Started process (PID=2247) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T18:49:34.059+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-24T18:49:34.059+0000] {logging_mixin.py:137} INFO - [2024-09-24T18:49:34.059+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T18:49:34.068+0000] {logging_mixin.py:137} INFO - [2024-09-24T18:49:34.068+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-24T18:49:34.068+0000] {logging_mixin.py:137} INFO - [2024-09-24T18:49:34.068+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-24T18:49:34.068+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T18:49:34.074+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2024-09-24T18:50:04.590+0000] {processor.py:153} INFO - Started process (PID=2458) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T18:50:04.590+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-24T18:50:04.591+0000] {logging_mixin.py:137} INFO - [2024-09-24T18:50:04.591+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T18:50:04.655+0000] {logging_mixin.py:137} INFO - [2024-09-24T18:50:04.654+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-24T18:50:04.655+0000] {logging_mixin.py:137} INFO - [2024-09-24T18:50:04.655+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-24T18:50:04.655+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T18:50:04.659+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.071 seconds
[2024-09-24T18:50:35.413+0000] {processor.py:153} INFO - Started process (PID=2669) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T18:50:35.413+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-24T18:50:35.413+0000] {logging_mixin.py:137} INFO - [2024-09-24T18:50:35.413+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T18:50:35.421+0000] {logging_mixin.py:137} INFO - [2024-09-24T18:50:35.421+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-24T18:50:35.421+0000] {logging_mixin.py:137} INFO - [2024-09-24T18:50:35.421+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-24T18:50:35.421+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T18:50:35.429+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2024-09-24T18:51:06.849+0000] {processor.py:153} INFO - Started process (PID=2880) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T18:51:06.852+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-24T18:51:06.856+0000] {logging_mixin.py:137} INFO - [2024-09-24T18:51:06.855+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T18:51:06.870+0000] {logging_mixin.py:137} INFO - [2024-09-24T18:51:06.870+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-24T18:51:06.871+0000] {logging_mixin.py:137} INFO - [2024-09-24T18:51:06.871+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-24T18:51:06.871+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T18:51:06.882+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2024-09-24T18:51:37.831+0000] {processor.py:153} INFO - Started process (PID=3098) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T18:51:37.832+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-24T18:51:37.834+0000] {logging_mixin.py:137} INFO - [2024-09-24T18:51:37.834+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T18:51:37.842+0000] {logging_mixin.py:137} INFO - [2024-09-24T18:51:37.842+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-24T18:51:37.842+0000] {logging_mixin.py:137} INFO - [2024-09-24T18:51:37.842+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-24T18:51:37.842+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T18:51:37.847+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2024-09-24T18:52:08.754+0000] {processor.py:153} INFO - Started process (PID=3310) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T18:52:08.756+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-24T18:52:08.756+0000] {logging_mixin.py:137} INFO - [2024-09-24T18:52:08.756+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T18:52:08.763+0000] {logging_mixin.py:137} INFO - [2024-09-24T18:52:08.763+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-24T18:52:08.763+0000] {logging_mixin.py:137} INFO - [2024-09-24T18:52:08.763+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-24T18:52:08.763+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T18:52:08.769+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2024-09-24T18:52:39.702+0000] {processor.py:153} INFO - Started process (PID=3519) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T18:52:39.703+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-24T18:52:39.704+0000] {logging_mixin.py:137} INFO - [2024-09-24T18:52:39.704+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T18:52:39.712+0000] {logging_mixin.py:137} INFO - [2024-09-24T18:52:39.712+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-24T18:52:39.712+0000] {logging_mixin.py:137} INFO - [2024-09-24T18:52:39.712+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-24T18:52:39.712+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T18:52:39.718+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2024-09-24T18:53:10.580+0000] {processor.py:153} INFO - Started process (PID=3730) to work on /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T18:53:10.581+0000] {processor.py:743} INFO - Processing file /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-24T18:53:10.581+0000] {logging_mixin.py:137} INFO - [2024-09-24T18:53:10.581+0000] {dagbag.py:532} INFO - Filling up the DagBag from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T18:53:10.589+0000] {logging_mixin.py:137} INFO - [2024-09-24T18:53:10.588+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-24T18:53:10.589+0000] {logging_mixin.py:137} INFO - [2024-09-24T18:53:10.589+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-24T18:53:10.589+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-24T18:53:10.595+0000] {processor.py:175} INFO - Processing /usr/local/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
