[2024-10-13T19:02:08.067+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_Demo.Email_notification manual__2024-10-13T19:01:13.576487+00:00 [queued]>
[2024-10-13T19:02:08.072+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_Demo.Email_notification manual__2024-10-13T19:01:13.576487+00:00 [queued]>
[2024-10-13T19:02:08.072+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2024-10-13T19:02:08.072+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2024-10-13T19:02:08.072+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2024-10-13T19:02:08.078+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): Email_notification> on 2024-10-13 19:01:13.576487+00:00
[2024-10-13T19:02:08.083+0000] {standard_task_runner.py:55} INFO - Started process 864 to run task
[2024-10-13T19:02:08.086+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'pipeline_Demo', 'Email_notification', 'manual__2024-10-13T19:01:13.576487+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_Demo.py', '--cfg-path', '/tmp/tmpwvtqcqiy']
[2024-10-13T19:02:08.087+0000] {standard_task_runner.py:83} INFO - Job 5: Subtask Email_notification
[2024-10-13T19:02:08.096+0000] {logging_mixin.py:137} WARNING - /usr/local/lib/python3.9/site-packages/***/settings.py:250 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-10-13T19:02:08.128+0000] {task_command.py:389} INFO - Running <TaskInstance: pipeline_Demo.Email_notification manual__2024-10-13T19:01:13.576487+00:00 [running]> on host c3a571b96d5f
[2024-10-13T19:02:08.190+0000] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=pipeline_Demo
AIRFLOW_CTX_TASK_ID=Email_notification
AIRFLOW_CTX_EXECUTION_DATE=2024-10-13T19:01:13.576487+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-10-13T19:01:13.576487+00:00
[2024-10-13T19:02:08.201+0000] {logging_mixin.py:137} WARNING - /opt/***/scripts/email_notification.py:119 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-10-13T19:02:08.201+0000] {email_notification.py:133} INFO - Error: Execution failed on sql '
    SELECT A.Pipeline, A.Run_id, A.Service, A.task_order, A.Source_Path_Table, A.Source_File_DML, 
           A.record_count AS Records, A.Target_Path_Table, A.Target_file, A.Status
    FROM public.pipeline_run_log A
    INNER JOIN (
        SELECT Pipeline, Run_id, Service, task_order, MAX(timestamp) AS maxt 
        FROM public.pipeline_run_log
        WHERE run_id = 'manual__2024-10-13T19:01:13.576487+00:00' 
        GROUP BY Pipeline, Run_id, Service, task_order
    ) B 
    ON A.pipeline = B.pipeline 
    AND A.run_id = B.run_id 
    AND A.task_order = B.task_order 
    AND A.timestamp = B.maxt
    ORDER BY task_order;
    ': relation "public.pipeline_run_log" does not exist
LINE 4:     FROM public.pipeline_run_log A
                 ^

[2024-10-13T19:02:08.202+0000] {python.py:177} INFO - Done. Returned value was: None
[2024-10-13T19:02:08.210+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=pipeline_Demo, task_id=Email_notification, execution_date=20241013T190113, start_date=20241013T190208, end_date=20241013T190208
[2024-10-13T19:02:08.224+0000] {local_task_job.py:212} INFO - Task exited with return code 0
[2024-10-13T19:02:08.242+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
