[2024-10-10T14:45:36.496+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_C.task_0_S3_to_S3 manual__2024-10-10T14:43:34.980978+00:00 [queued]>
[2024-10-10T14:45:36.499+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_C.task_0_S3_to_S3 manual__2024-10-10T14:43:34.980978+00:00 [queued]>
[2024-10-10T14:45:36.500+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2024-10-10T14:45:36.500+0000] {taskinstance.py:1289} INFO - Starting attempt 2 of 2
[2024-10-10T14:45:36.500+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2024-10-10T14:45:36.505+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): task_0_S3_to_S3> on 2024-10-10 14:43:34.980978+00:00
[2024-10-10T14:45:36.512+0000] {standard_task_runner.py:55} INFO - Started process 3324 to run task
[2024-10-10T14:45:36.518+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'pipeline_C', 'task_0_S3_to_S3', 'manual__2024-10-10T14:43:34.980978+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_C.py', '--cfg-path', '/tmp/tmpl_r33rzq']
[2024-10-10T14:45:36.523+0000] {standard_task_runner.py:83} INFO - Job 3: Subtask task_0_S3_to_S3
[2024-10-10T14:45:36.534+0000] {logging_mixin.py:137} WARNING - /usr/local/lib/python3.9/site-packages/***/settings.py:250 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-10-10T14:45:36.557+0000] {task_command.py:389} INFO - Running <TaskInstance: pipeline_C.task_0_S3_to_S3 manual__2024-10-10T14:43:34.980978+00:00 [running]> on host 1f7125be5d21
[2024-10-10T14:45:36.589+0000] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=pipeline_C
AIRFLOW_CTX_TASK_ID=task_0_S3_to_S3
AIRFLOW_CTX_EXECUTION_DATE=2024-10-10T14:43:34.980978+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-10-10T14:43:34.980978+00:00
[2024-10-10T14:45:36.688+0000] {s3_s3.py:42} INFO - Executing File pattern check......
[2024-10-10T14:45:37.099+0000] {s3_s3.py:82} INFO - No files found at s3a://sdevalla-buck/test/target/reddit_target_yyyymmdd.csv with input pattern
[2024-10-10T14:45:37.101+0000] {s3_s3.py:145} ERROR - Unable to get file of provided pattern...
[2024-10-10T14:45:37.102+0000] {s3_s3.py:283} INFO - File Transfer Failed!
[2024-10-10T14:45:37.102+0000] {python.py:177} INFO - Done. Returned value was: None
[2024-10-10T14:45:37.113+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=pipeline_C, task_id=task_0_S3_to_S3, execution_date=20241010T144334, start_date=20241010T144536, end_date=20241010T144537
[2024-10-10T14:45:37.130+0000] {local_task_job.py:212} INFO - Task exited with return code 0
[2024-10-10T14:45:37.143+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
