[2024-10-11T03:29:14.464+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_s3_db_test_1.task_0_S3_to_DB manual__2024-10-11T03:29:11.539652+00:00 [queued]>
[2024-10-11T03:29:14.469+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_s3_db_test_1.task_0_S3_to_DB manual__2024-10-11T03:29:11.539652+00:00 [queued]>
[2024-10-11T03:29:14.469+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2024-10-11T03:29:14.470+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2024-10-11T03:29:14.470+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2024-10-11T03:29:14.475+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): task_0_S3_to_DB> on 2024-10-11 03:29:11.539652+00:00
[2024-10-11T03:29:14.482+0000] {standard_task_runner.py:55} INFO - Started process 25442 to run task
[2024-10-11T03:29:14.484+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'pipeline_s3_db_test_1', 'task_0_S3_to_DB', 'manual__2024-10-11T03:29:11.539652+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_s3_db_test_1.py', '--cfg-path', '/tmp/tmpceevqp9y']
[2024-10-11T03:29:14.485+0000] {standard_task_runner.py:83} INFO - Job 33: Subtask task_0_S3_to_DB
[2024-10-11T03:29:14.505+0000] {logging_mixin.py:137} WARNING - /usr/local/lib/python3.9/site-packages/***/settings.py:250 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-10-11T03:29:14.567+0000] {task_command.py:389} INFO - Running <TaskInstance: pipeline_s3_db_test_1.task_0_S3_to_DB manual__2024-10-11T03:29:11.539652+00:00 [running]> on host d6685a94b59c
[2024-10-11T03:29:14.637+0000] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=pipeline_s3_db_test_1
AIRFLOW_CTX_TASK_ID=task_0_S3_to_DB
AIRFLOW_CTX_EXECUTION_DATE=2024-10-11T03:29:11.539652+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-10-11T03:29:11.539652+00:00
[2024-10-11T03:29:14.644+0000] {s3_db.py:130} INFO - Executing S3 File read.......
[2024-10-11T03:29:14.644+0000] {s3_db.py:17} INFO - Creating Spark session ......
[2024-10-11T03:29:24.784+0000] {s3_db.py:72} INFO - Executing File pattern check......
[2024-10-11T03:29:24.789+0000] {logging_mixin.py:137} INFO - prefix: test
[2024-10-11T03:29:25.521+0000] {s3_db.py:117} INFO - Latest file for pattern - sftp_\d{8}\.txt at s3a://sdevalla-buck/test: sftp_20241010.txt
[2024-10-11T03:29:30.241+0000] {s3_db.py:52} INFO - Updating run log for read operation....
[2024-10-11T03:29:30.244+0000] {s3_db.py:60} INFO - Error: invalid input syntax for type integer: "None"
LINE 1: ...','80344945-a749-4b86-9553-4d6122badc23','S3-DB', 'None','s3...
                                                             ^

[2024-10-11T03:29:30.246+0000] {s3_db.py:239} INFO - Executing file writing function .....
[2024-10-11T03:29:30.972+0000] {s3_db.py:264} INFO - Completed writing to target table.......
[2024-10-11T03:29:30.972+0000] {s3_db.py:317} INFO - Updating run_log, marking status as success........ 
[2024-10-11T03:29:30.974+0000] {s3_db.py:52} INFO - Updating run log for write operation....
[2024-10-11T03:29:30.975+0000] {s3_db.py:60} INFO - Error: invalid input syntax for type integer: "None"
LINE 1: ...','80344945-a749-4b86-9553-4d6122badc23','S3-DB', 'None','s3...
                                                             ^

[2024-10-11T03:29:30.975+0000] {s3_db.py:319} INFO - 918 records transferred from s3a://sdevalla-buck/test/sftp_yyyymmdd.txt to ***.reddit_d
[2024-10-11T03:29:31.355+0000] {python.py:177} INFO - Done. Returned value was: 918
[2024-10-11T03:29:31.408+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=pipeline_s3_db_test_1, task_id=task_0_S3_to_DB, execution_date=20241011T032911, start_date=20241011T032914, end_date=20241011T032931
[2024-10-11T03:29:31.453+0000] {local_task_job.py:212} INFO - Task exited with return code 0
[2024-10-11T03:29:31.492+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
